name: Express Blue/Green CD

on:
  push:
    branches:
      - main
    # workflow_run:
    #   workflows: ["Express Blue/Green CI"]
    #   types:
    #     - completed
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' <<EOF
          set -e

          cd /home/${{ secrets.SERVER_USER }}/bluegreen

          if docker ps | grep express-healthcheck-blue; then
            TARGET=green
            STOP=express-healthcheck-blue
          elif docker ps | grep express-healthcheck-green; then
            TARGET=blue
            STOP=express-healthcheck-green
          else
            TARGET=blue
            STOP=
          fi

          echo "Deploying to: \$TARGET"
          docker compose pull express-healthcheck-\$TARGET
          docker compose up -d express-healthcheck-\$TARGET

          if [ "\$STOP" != "none" ]; then
            echo "Running health check..."

            if [ "\$TARGET" == "blue" ]; then
              PORT=3001
            elif [ "\$TARGET" == "green" ]; then
              PORT=3002
            else
              echo "Unknown target color: \$TARGET"
              exit 1
            fi

            for i in {1..10}; do
              sleep 2
              if curl --fail -s http://localhost:\$PORT/health; then
                echo "Health check passed"
              elif [ \$i -eq 10 ]; then
                echo "Health check failed. Rolling back..."
                docker stop express-healthcheck-\$TARGET
                docker compose restart \$STOP
                exit 1
              fi
            done
          else
            echo "First deploy - skipping health check"
          fi

          echo "Switching Nginx to \$TARGET"
          sed -i "s/express-healthcheck-[a-z]\\+/express-healthcheck-\$TARGET/g" nginx.conf
          docker stop nginx-proxy || true
          docker rm -f nginx-proxy || true
          docker compose up -d nginx-proxy

          if [ "\$STOP" != "none" ]; then
            docker stop \$STOP || true
          fi
          EOF
